# Bash aliases.
# This file should be sourced from .bashrc.

# clear
alias c='/usr/bin/clear'

# ctags
alias ctags='ctags --fields=+l'

# go
#alias rgo='richgo'
alias gotest='go test -v -race -failfast -p 4 -timeout 0 -count 1'

# grep
alias grep='grep --color=auto'
alias rgrep='grep -R'

# make less more friendly for non-text input files see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# ls
alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -alF'
alias l='ls -CF'

# man
alias man='man -P less'

# state
alias s='[[ -z ${ACTIVESTATE_ACTIVATED} ]] && echo "Not in an activated state" || echo "Activated: $ACTIVESTATE_ACTIVATED"'

# fix wsl2 not synching time
alias fix-time='sudo hwclock -s'
